name: com.xiaoyoushijie.app
description: English learning lover community.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+196

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  file: ^7.0.0
  dio: ^5.5.0+1
  shared_preferences: ^2.0.5
  google_fonts: ^4.0.4
  provider: ^6.0.3
  webview_flutter: ^4.8.0
  url_launcher: ^6.3.0
  cached_network_image: ^3.4.0
  wechat_assets_picker: ^8.8.1+1 # 照片选择器
  photo_manager: ^3.0.0-dev.2
  image_picker: ^0.8.9
  image_cropper: ^5.0.0
  photo_view: ^0.14.0
  video_player: ^2.8.3
  # Video fullscreen play
  chewie: ^1.8.3
  easy_refresh: ^3.3.2+1
  video_compress_v2: ^1.0.0+1 # 用于视频压缩和格式转换 mov to mp4
  fluttertoast: ^8.2.2
  extended_image: ^8.1.1
  flutter_image_compress: ^2.3.0
  #sqlite
  sqflite: ^2.2.8+4
  device_info_plus: ^11.1.0
  package_info_plus: ^8.3.1
  path_provider: ^2.1.5
  install_plugin: ^2.1.0
  steel_crypt: ^3.0.0+1
  #角标
  badges: ^3.1.2
  # 虚线
  dashed_rect: ^0.0.4
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo_32x32.png
    - assets/images/logo_64x64.png
    - assets/images/logo_128x128.png
    - assets/images/play.png
    - assets/images/play_64x64.png
    - assets/images/launch_image.png
    - assets/images/logo_64x64_fff.png

  fonts:
    - family: LatterIcons
      fonts:
        - asset: assets/fonts/LatterIcons.ttf
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
        - asset: assets/fonts/HelveticaNeue400.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNeue500.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeue600.ttf
          weight: 600
        - asset: assets/fonts/HelveticaNeue700.ttf
          weight: 700
        - asset: assets/fonts/HelveticaNeue800.ttf
          weight: 800
        - asset: assets/fonts/HelveticaNeue900.ttf
          weight: 900
        - asset: assets/fonts/HelveticaNeueIt.ttf
          style: italic

flutter_intl:
  enabled: true
  Intl:
    defaultLocale: 'zh_CN'
